site_name: TickLab - Start here, go anywhere
site_url: https://ngyngcphu.github.io/mkdocs-tool/
site_author: Nguyen Ngoc Phu
site_description: Summary of all knowledge sharing articles covering the fields of scientific research and project development.

repo_name: ngyngcphu/mkdocs-tool
repo_url: https://github.com/ngyngcphu/mkdocs-tool

copyright: Copyright &copy; 2023 TickLab. Made by Engineering team.

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
  favicon: assets/TickLab-logo.svg
  logo: assets/TickLab-logo.svg
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Git workflow: 
    - git-workflow/index.md
    - Git-branch workflow: git-workflow/git-branch-workflow.md
    - Github Project: git-workflow/github-project.md
    #- Resolve conflict: git-workflow/resolve-conflict.md
    - Sample Project: git-workflow/sample-project.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
