authors:
  ngyngcphu:
    name: Nguyễn Ngọc Phú
    description: Software developer
    avatar: https://avatars.githubusercontent.com/u/111476687?v=4
  amyranotamirror:
    name: Nguyễn Thanh Hiền
    description: Business Analyst & UI/UX Designer
    avatar: https://avatars.githubusercontent.com/u/87921251?v=4
  quannhg:
    name: Nguyễn Hồng Quân
    description: Software developer
    avatar: https://avatars.githubusercontent.com/u/128902312?v=4

